### PR TITLE
Fixed FD-38641 - Bulk asset edit unable to update model_id, misc other bugs

### LINKED ISSUE #13774: Bulk Edit not working when only 1 asset selected
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When selecting only 1 asset from a list of assets and attempting to bulk edit (i.e. to update Current location and default location), the values are not updated after save.

### Reproduction steps

1.Show a list of assets
2. check **one** list row
3. choose **Edit** from the top left dropdown
4. select **Go**
5. uncheck **Delete values for this asset**
6. change location
7. Leave radio **Update default location AND actual location** selected
8. press **Save**
...

### Expected behavior

Location and Default location of the selected asset are updated

### Screenshots

_No response_

### Snipe-IT Version

v6.2.3 - build 11759 (master)(hosted)

### Operating System

hosted

### Web Server

hosted

### PHP Version

hosted

### Operating System

MacOS Sonoma

### Browser

Google Chrome

### Version

118.0.5993.96 (Official Build) (x86_64)

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snipe**
A customer in our [Discord channel](https://discord.gg/yZFtShAcKk) discovered a bug where he was having problems updating the model of assets that had custom fields. Once I went down that rabbit hole, I found a few more potential optimizations with some refactoring.

Since I was in there, I did a little extra work, namely:

- making the meta log output nicer (God I hate JavaScript)
- adding a "unique" icon to the custom fields page so you can easily see which fields require unique constraints
- fixed the checkbox/radio button display - I had missed them when we moved away from iCheck so I hadn't realized they looked so weird
- Added some new custom fields seeders so we have a few more examples to make testing this easier
- Fixed #13774 (I think)

### Bulk Update
https://github.com/snipe/snipe-it/assets/197404/2a236731-52e9-4eea-8e6f-6a66c65f1369

### Unique indicator
https://github.com/snipe/snipe-it/assets/197404/260d022a-54d1-4366-9209-6568637085bf

### Nicer changelog
Screenshot 2023-10-26 at 9 31 03 AM

### Next Up
I'd still like to continue down the refactor path and see if we can't make that a less chonk set of queries. It's kinda slow right now, and a lot of them are repeats. Some of this will be from the validation where we're checking to make sure that the location, etc actually exists in the database (which I know we have all pontificated on solutions for) but there are also just kind of a bunch we could probably tighten up.

I'd also like to better handle #13798 - we do this already for some fields but not all. It's going to be annoying, but it will be less confusing. (Basically, right now, you can't blank out a lot of the fields - they just default to whatever they were before unless you submit *something*.)

### CODE REVIEW

File: app/Observers/AssetObserver.php [hunk 1]
```diff
@@ -11,7 +11,7 @@
 class AssetObserver
 {
     /**
-     * Listen to the User created event.
+     * Listen to the User updating event. This fires automatically every time an asset is saved.
```
Comment (uberbrady) [inline app/Observers/AssetObserver.php]: Might want to update this to say when an _existing_ asset is saved. "Asset is saved" might translate for some developers to `$asset->save()` - which can be an `updating` event or `creating` event, but is always a `saving` event.

File: database/factories/ActionlogFactory.php [hunk 2]
```diff
@@ -38,7 +38,7 @@ public function assetCheckoutToUser()
     {
         return $this->state(function () {
             $target = User::inRandomOrder()->first();
-            $asset = Asset::RTD()->inRandomOrder()->first();
+            $asset = Asset::inRandomOrder()->RTD()->first();
```
Comment (uberbrady) [inline database/factories/ActionlogFactory.php:41]: This seems superfluous? But I can't say that I mind too much.

File: database/factories/CustomFieldFactory.php [hunk 3]
```diff
@@ -26,6 +26,7 @@ public function definition()
             'format' => '',
             'element' => 'text',
             'auto_add_to_fieldsets' => '0',
+            'show_in_requestable_list' => '0',
```
Comment (uberbrady) [inline database/factories/CustomFieldFactory.php:29]: Did this leak in from your work on the 'show in requestable' feature?

File: database/factories/CustomFieldFactory.php [hunk 4]
```diff
@@ -66,6 +67,7 @@ public function cpu()
             return [
                 'name' => 'CPU',
                 'help_text' => 'The speed of the processor on this device.',
+                'show_in_requestable_list' => '1',
```
Comment (uberbrady) [inline database/factories/CustomFieldFactory.php:70]: ditto?

File: resources/views/partials/bootstrap-table.blade.php [hunk 5]
```diff
@@ -530,15 +530,42 @@ function groupsFormatter(value) {
 
 
     function changeLogFormatter(value) {
+
+        console.dir(value);
```
Comment (uberbrady) [inline resources/views/partials/bootstrap-table.blade.php]: probably want to pull this - debugging code

File: resources/views/partials/bootstrap-table.blade.php [hunk 6]
```diff
@@ -530,15 +530,42 @@ function groupsFormatter(value) {
...
         var result = '';
+        var pretty_index = '';
+
+        console.error('first the formatter');
```
Comment (uberbrady) [inline resources/views/partials/bootstrap-table.blade.php]: moar debugz

File: resources/views/partials/bootstrap-table.blade.php [hunk 7]
```diff
@@ -530,15 +530,42 @@ function groupsFormatter(value) {
...
+
             for (var index in value) {
-                result += index + ': <del>' + value[index].old + '</del>  <i class="fas fa-long-arrow-alt-right" aria-hidden="true"></i> ' + value[index].new + '<br>'
+
+
+                // Check if it's a custom field
+                if (index.startsWith('_snipeit_')) {
+                    console.error('It is a custom field');
```
Comment (uberbrady) [inline resources/views/partials/bootstrap-table.blade.php]: debugz

File: resources/views/partials/bootstrap-table.blade.php [hunk 8]
```diff
@@ -530,15 +530,42 @@ function groupsFormatter(value) {
...
+                    pretty_index = index.replace("_snipeit_", "Custom:_");
+                } else {
+                    console.error('Not a custom field');
```
Comment (uberbrady) [inline resources/views/partials/bootstrap-table.blade.php]: debugz

File: app/Http/Controllers/Assets/BulkAssetsController.php [hunk 9]
```diff
@@ -208,61 +208,86 @@ public function update(Request $request)
...
+                                    $decrypted_old = Helper::gracefulDecrypt($field, $asset->{$field->db_column});
+
+                                    // Check if the decrypted existing value is different from one we just submitted
+                                    // and if not, pull it out of the object
+                                    if ($decrypted_old != $this->update_array[$field->db_column]) {
+                                        $asset->{$field->db_column} = \Crypt::encrypt($this->update_array[$field->db_column]);
+                                    } else {
+                                        \Log::debug('The decrypted existing value is the same as the one submitted - unset it');
+                                        unset($this->update_array[$field->db_column]);
+                                        unset($asset->{$field->db_column});
```
Comment (uberbrady) [inline app/Http/Controllers/Assets/BulkAssetsController.php:255]: This spooked me for a second and made me think that we were *blanking* the custom field property - but we're not, we're saying it's not-changed and thus doesn't need to get re-encrypted here. I think a comment for something like that would be helpful.

File: app/Http/Controllers/Assets/BulkAssetsController.php [hunk 10]
```diff
@@ -208,61 +208,86 @@ public function update(Request $request)
...
+                                }
+
+                            } // endforeach
+                    } // end custom field check
+                } // end custom fields handler
+
+
+
+                // Check if it passes validation, and then try to save
+                if (!$asset->update($this->update_array)) {
```
Comment (uberbrady) [inline app/Http/Controllers/Assets/BulkAssetsController.php:282]: I think this is Laravel being confusing - but in my head the `->update()` method means "change the values on the actual object, but don't fire `save()` yet. But I might be mistaken because in the context of bulk actions, it's just a straight SQL `UPDATE` query. So if this *does* work as intended, my bad. But my concern here is that the Watson Validating trait won't have the opportunity to fire yet because it's not doing the `save()`? So it will never fail this `if()` clause. But, again, I could be mistaken.

File: app/Http/Transformers/ActionlogsTransformer.php [hunk 11]
```diff
@@ -98,6 +100,13 @@ public function transformActionlog (Actionlog $actionlog, $settings = null)
                                         \Log::debug('custom fields do not match');
                                         $clean_meta[$fieldname]['old'] = "************";
                                         $clean_meta[$fieldname]['new'] = "************";
+
+                                        // Display the changes if the user is an admin or superadmin
+                                        if (Gate::allows('admin')) {
+                                            $clean_meta[$fieldname]['old'] = ($enc_old) ? unserialize($enc_old): '(blank)';
```
Comment (uberbrady) [inline app/Http/Transformers/ActionlogsTransformer.php]: Should we be using a translation string here?

**Review by uberbrady — COMMENTED** [review]
I have a few little concerns here - only one of which should change any kind of functionality. But if you've tested this, then my concern (about the `->update()` method on a single Eloquent object) is very likely incorrect. Some other pieces are just asking for some updated comments.

File: database/factories/ActionlogFactory.php (hunk 2 above)
Comment (snipe) [reply database/factories/ActionlogFactory.php:41]: It was in the wrong order and was causing the seeder to fail.

File: database/factories/CustomFieldFactory.php (hunk 3 above)
Comment (snipe) [reply database/factories/CustomFieldFactory.php:29]: Yes - since I was messing with the seeders anyway, I figured I'd add that in as well.

File: database/factories/CustomFieldFactory.php (hunk 4 above)
Comment (snipe) [reply database/factories/CustomFieldFactory.php:70]: Ditto.

File: app/Http/Controllers/Assets/BulkAssetsController.php (hunk 10 above)
Comment (snipe) [reply app/Http/Controllers/Assets/BulkAssetsController.php:282]: It definitely catches on validation

File: app/Http/Transformers/ActionlogsTransformer.php (hunk 11 above)
Comment (snipe) [reply app/Http/Transformers/ActionlogsTransformer.php]: Probably

Comment (snipe) [reply app/Http/Transformers/ActionlogsTransformer.php]: I changed it to `''` instead to make it more consistent with the non-custom fields

**Review by uberbrady — APPROVED** [review]
This is a really nice collection of fixups and improvements, and I think it makes a lot of sense. Nice work!

**Review by marcusmoore — COMMENTED** [review]
Looks good 👍🏾
