### PR TITLE
Fixed #13317 Accessories declined by user remain assigned

### LINKED ISSUE #13317: Assets declined by user remain assigned
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I activate the option for users to accept or reject the assets or accessories assigned by the administrator.

The problems I have are 2:

1.- Even if the user rejects the assignment of the asset, it is still assigned with the rejected status in the history.

2.- The user signs the request but rejects it, the signature is not shown in the user's history. The signature is only shown when you accept the assets or accessories.

### Reproduction steps

1. I assign the asset

2. the user rejected

3. the asset is assigned to him

4. sign the rejection but the signature does not appear

### Expected behavior

I assign the asset

the user rejects and places his signature

the asset or accessory is not assigned to you, it remains in stock

in the user's history your application appears rejected and with the signature

### Screenshots

_No response_

### Snipe-IT Version

6.1.2

### Operating System

Windows

### Web Server

Apache

### PHP Version

8

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by inietov**
# Description
When an accessory is checked out and acceptance is required, if the user rejects the asset it remains assigned to them. This is contrary to the behavior on assets which are unassigned if declined, so I added the `declinedCheckout` method to the Accessory model.

Then, as the linked issue remarks, the signature when the asset is rejected is not showed in history. I also add this to the declined item functionality. Maybe is a little out of scope, but I think it's a small change and can be made here.

Fixes #13317 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
**Test Configuration**:
* PHP version: 8.1
* MySQL version: 8.0.31
* Webserver version: PHP dev server
* OS version: Debian 11

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/Models/Accessory.php [hunk 1]
```diff
@@ -32,6 +32,16 @@ class Accessory extends SnipeModel
...
+
+    public function declinedCheckout(User $declinedBy, $signature)
+    {
+        if (is_null($accessory_user = \DB::table('accessories_users')->where('assigned_to', $declinedBy->id)->where('accessory_id', $this->id)->latest('created_at'))) {
+            // Redirect to the accessory management page with error
+            return redirect()->route('accessories.index')->with('error', trans('admin/accessories/message.does_not_exist'));
+        }
+
+        $accessory_user->limit(1)->delete();
+    }
```
Comment (marcusmoore) [inline app/Models/Accessory.php]: Can we move this method lower in the class so the properties (ie `$searchableAttributes`, `$searchableRelations`, `$rules`) aren't separated?

I just did a quick look but under the `numRemaining()` method seems like an ok place.

**Review by marcusmoore — APPROVED** [review]
I tested this locally and it works 👍🏾 

One minor request but overall good stuff 😄

**Review by spencerrlongg — APPROVED** [review]

**Comment by inietov** [comment]
Kindly pinging @snipe, this looks ok to you? or need some more work?
