### PR TITLE
Fixes #11096 Backup created_at time is incorrect

### LINKED ISSUE #11096: v6 - Backup created_at time is incorrect
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I've using v5.4.4 has no issues with the following, but once upgrade to v6.0.0, then I've noticed the below:

1. I've configure TimeZone = 'Asia/Kuala_Lumpur' in .env file. The backup file name's appears correctly but in the Snipe-IT Backup display page showing the wrong Time Zone.
2. No matter how many times log in to the Snipe-IT, the Login Attemps always empty and not been recorded as shown in the picture.
Bug-Backup
Bug-LoginAttepts

### Reproduction steps

Bug for Backup Time Zone
1. Configure .env file APP_TIMEZONE='Asia/Kuala_Lumpur'
2. Generate Backup in Backup page

Bug for Login Attempts
1. Login any user to Snipe-IT
2. Browse the "Login Attempts", it shows empty.

### Expected behavior

Backup Time Zone:

The "Created" date time in Backup page must follow what I've set in the .env file APP_TIMEZONE value.

Login Attempts:

Any user login must shows in this page.

### Screenshots

_No response_

### Snipe-IT Version

v6.0.0

### Operating System

Windows Server 2016

### Web Server

IIS

### PHP Version

7.4.29 VC15 x64 Non Thread Safe (2022-Apr-14 21:34:21)

### Operating System

Windows 10 Pro

### Browser

Chrome / Edge / Mozilla

### Version

101

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by inietov**
# Description
We used to display the backups dates using the `date()` function, but for v6 we changed to `Helper::getFormattedDateObject()` that uses Carbon to format the date. Where we shouldn't have any problem because we use UNIX timestamps to show the date, but I believe that in Carbon the timezone is defaulting to UTC, and don't care of the timezone that we have in the env file.

So, as I didn't want to affect the Helper function that we use in other places, I just formatted the timestamp as we used to make it before.

Fixes #11096 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
**Test Configuration**:
* PHP version: 7.4.16
* MySQL version: 8.0.23
* Webserver version: nginx/1.19.8
* OS version: Debian 10

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Thanks - we're definitely going to get people complaining that the date isn't formatted the way they selected in the settings tho. :(

File: app/Http/Controllers/SettingsController.php [hunk 1]
```diff
@@ -1044,7 +1044,7 @@ public static function getPDFBranding()
      */
     public function getBackups()
     {
-
+        $settings = Setting::getSettings();
```
Comment (inietov) [inline app/Http/Controllers/SettingsController.php:1047]: > Thanks - we're definitely going to get people complaining that the date isn't formatted the way they selected in the settings tho. :(

I fixed that too, here I get the settings, and later I put the format accord to this,
