### PR TITLE
Fixed #9949 - PATCH to custom fields failing on validation (alt approach to #12011)

### LINKED ISSUE #9949: Unable to update field values for custom field without changing the name
#### Please confirm you have done the following before posting your bug report:

- [ n/a ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When using the PUT for the 'fields/:id' endpoint to update a custom field's "field_values" for element type "listbox", the 'name' value is required, despite the field number already being specified. We don't want to update the name, so we tried using the same name, but we get the error, "The name has already been taken." 

Since we're only updating the listbox values, we shouldn't have to supply a name when the field id has already been passed in the URL. When using no 'name' value, it returns an error saying that the 'name' field is required.

**To Reproduce**
1. Use the /fields/:id PUT endpoint to update the listbox of a custom field.
2. In the JSON, omit the name, or use the same name as the field you're updating.
3. Error: Returns that the name field is required or that the name is already in use.

**Expected behavior**
Should not have to provide a name for an update action when the field ID is already supplied.

**Server (please complete the following information):**
 - Hosted Snipe-IT, v5.1.6

**Desktop (please complete the following information):**
 - Insomnia, PHP

### PR DESCRIPTION
**Pull request by snipe**
This is an alternate solution to the issue where patches to the custom fields API would require you to pass the name (and would fail if it wasn't unique). @inietov had a proposed solution in #12011 which is meant to fix #9949, but this is a slightly different angle which may or may not be more consistent with how we handle this issue elsewhere. We still have to use `$validator = Validator::make($data, $field->validationRules($regex_format));` in the controllers since we have to pass some dynamic info (regex) into that validator and the `protected $rules` won't allow that. 

I'd love some eyeballs on this though, from both @uberbrady and @inietov <3

### CODE REVIEW

File: app/Models/CustomField.php [hunk 1]
```diff
@@ -48,7 +48,11 @@ class CustomField extends Model
      *
      * @var array
      */
-    protected $rules = [];
+    protected $rules = [
+        'name' => 'required|unique:custom_fields',
+        'element' => 'required','in:text,listbox,textarea,checkbox,radio',
```
Comment (uberbrady) [inline app/Models/CustomField.php]: I think this should be `required|in:text,listbox,textarea,checkbox,radio`?

File: app/Models/CustomField.php [hunk 2]
```diff
@@ -48,7 +48,11 @@ class CustomField extends Model
...
+        'field_encrypted' => 'nullable|boolean',
+    ];
```
Comment (uberbrady) [inline app/Models/CustomField.php:55]: I feel like we could add:

```php
'format' => [
                 Rule::in(array_merge(array_keys(self::PREDEFINED_FORMATS), self::PREDEFINED_FORMATS, [$regex_format])),
             ],
```
      
that right into the model-level validation rules, right? Then we could get rid of the `validationRules` method entirely (which I *think* was trying to something else entirely but got transmogrified somehow into subsuming model-level validation...)

Comment (uberbrady) [reply app/Models/CustomField.php:55]: (Because when we actually *call* `validationRules()` we don't seem to use the parameter at all)

**Review by uberbrady — CHANGES_REQUESTED** [review]
This seems like a solid move in the right direction here - I always prefer model-level validation so that you know that *whenever* you're using a particular model, that it always has passed some sort of validation. (Of course, we've run into the drawbacks of that approach, but I still think the benefits outweigh the drawbacks).

I think - unless I'm missing something, which is absolutely possible - that we can put *all* of the model-level validation into the `$rules` attribute and then not have to explicitly invoke a validator at all. I would definitely run through the code real quick and see if the `validationRules()` method is used anywhere else, or ever called with a real parameter - based on how that method looks, I suspect not. Other comments are in-line.

I think this is a solid cleanup and if we can take it one step further our code will be much nicer!

File: app/Models/CustomField.php (hunk 2 above)
Comment (snipe) [reply app/Models/CustomField.php:55]: We do though, it's right in the PR text. `$validator = Validator::make($data, $field->validationRules($regex_format));`

Comment (snipe) [reply app/Models/CustomField.php:55]: https://github.com/snipe/snipe-it/blob/5661e69520851b95dc341f17993fce2c8cab95d0/app/Http/Controllers/Api/CustomFieldsController.php#L103

Comment (uberbrady) [reply app/Models/CustomField.php:55]: You're right, but I still suspect that we could get rid of the `validationRules` method completely because it's only invoked on Custom Field *creation* (or update). So really just model-level validation will do. The way we validate the *contents* of the custom field (within the asset) is by overriding the `save()` method on the asset - which does *not* call this method.

**Review by uberbrady — APPROVED** [review]
This is still a good enough step in the right direction that I'll accept it. I mentioned another thing in-line, but I totally get your point that you don't want to change too many things at once. Thanks!
