### PR TITLE
Fixed #8188 - Added Last Name as an email format

### LINKED ISSUE #8188: Import not displaying in Production
My import page is only showing the header - view source is showing that the input button & progress bar are in there, they are just not rendering - nor is the current file/progress table. 

Input appears to function correctly when in debug mode.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install 
- Version of Snipe-IT you're running -  **Version v4.9.3 - build 4395 (master)**
- Version of PHP you're running - **7.4.3**
- Version of MySQL/MariaDB you're running - **10.3.22**
- What OS and web server you're running Snipe-IT on - **Ubunto 20.04 LTS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **manual install from git**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - **no error.**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **/import**
- If a stacktrace is provided in the error, include that too. - **no error**
- Any errors that appear in your browser's error console. - **no errors**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - **no**
- Include any additional information you can find in `storage/logs` and your webserver's logs. - **No errors**
- Include what you've done so far in the installation, and if you got any error messages along the way. - **customised the resources/views/hardware/labels.blade.php - otherwise vanilla**
- Indicate whether or not you've manually edited any data directly in the database - **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

### PR DESCRIPTION
**Pull request by akemidx**
Making it so you can choose only Last Name

Screenshot 2025-04-03 at 11 42 14 PM

This addresses issue [#8188](https://github.com/snipe/snipe-it/issues/8118)

### CODE REVIEW

**Comment by snipe** [comment]
Can you resolve these conflicts?

File: resources/lang/en-US/general.php [hunk 1]
```diff
@@ -186,6 +186,7 @@
     'last'					=> 'Last',
     'last_login'            => 'Last Login',
     'last_name'             => 'Last Name',
+    'last_name_format'		=> 'Last Name (doe@example.com)',
```
Comment (snipe) [inline resources/lang/en-US/general.php]: I feel like having these in two places is kinda confusing. I'd probably opt to make a new array in the `resources/lang/en-US/admin/settings/general.php` with format translations.

Comment (snipe) [reply resources/lang/en-US/general.php]: Something like (in `admin/settings/general.php`):

```php
    'email_formats' => [
        'last_name_format' => 'Last Name (doe@example.com)',
        'first_name_format' => 'First Name (jane@example.com)',
	... etc
    ],
```

and 

```php
    'username_formats' => [
        'last_name_format' => 'Last Name (doe)',
        'first_name_format' => 'First Name (jane)',
	... etc
    ],
```

just so that they're visually closer to each other, since they basically do the same general thing.

Comment (akemidx) [reply resources/lang/en-US/general.php]: yea, that would be better. alrighty.

**Comment by snipe** [comment]
Looks good!
