### PR TITLE
Fixed #10866 - Checkin time always shows 12am

### LINKED ISSUE #10866: Checkin time always show 12AM
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When you try to check in an asset the dashboard always show 12AM checkin time

### Reproduction steps

1.
2.
3.
...

### Expected behavior

show correct check in time

### Screenshots

_No response_

### Snipe-IT Version

5.4.1; 6.0

### Operating System

win

### Web Server

apache2

### PHP Version

7.4

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description

Gives the proper time in the action logs when checking in an asset

Fixes # (issue)
#10866 
## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/Http/Controllers/Assets/AssetCheckinController.php [hunk 1]
```diff
@@ -106,9 +106,9 @@ public function store(AssetCheckinRequest $request, $assetId = null, $backto = n
             $asset->location_id = e($request->get('location_id'));
         }
 
-        $checkin_at = date('Y-m-d');
-        if ($request->filled('checkin_at')) {
-            $checkin_at = $request->input('checkin_at');
+        $checkin_at = date('Y-m-d H:i:s');
+        if (($request->filled('checkin_at')) && ($request->get('checkin_at') != date('Y-m-d'))) {
+            $checkin_at = $request->get('checkout_at');
```
Comment (uberbrady) [inline app/Http/Controllers/Assets/AssetCheckinController.php]: I think this is a typo - should that be `checkin_at`?

**Review by uberbrady — CHANGES_REQUESTED** [review]
Nice work! I think you might've put a wrong thing in the checkin_at piece there though?

**Review by uberbrady — APPROVED** [review]
Excellent!!!
