### PR TITLE
Fix Select2 'infinite scroll' drop-downs for Snipe-IT v5

### LINKED ISSUE #8035: Drop down menus will Break if their are less than six elements
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Drop-down menus will display items for a period of time until it shows "The results could not be Loaded".  This will prevent all drop down menus from work for a short period of time.

**To Reproduce**
1. Go to 'Login to the Demo on snipe-it website '
2. Click on '"Create New" -> Asset . Click on Company Drop-down list '
3. Scroll down to 'the bottom until you see "Loading More Results" and wait for 10 to 15 seconds'
4. See error 'Menu items disappear and "The Results could not be loaded" appears. This will also break all other drop down menus on the app for a short period of time'.

**Screenshots**
error

**Server (please complete the following information):**
 - Snipe-IT Version Master(v4.9.2)(DEMO)
 - OS: [unknown]
 - Web Server: [unknown]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [latest]

**Smartphone (please complete the following information):**

### PR DESCRIPTION
**Pull request by uberbrady**
As in PR #8227 - we need to correctly return whether or not there are 'more' results to return from the AJAX endpoint for Select2 - this makes the same change against the v5 branch.

This fixes #8035 for v5

### CODE REVIEW

File: app/Http/Transformers/SelectlistTransformer.php [hunk 1]
```diff
@@ -33,7 +33,7 @@ public function transformSelectlist (LengthAwarePaginator $select_items)
         }
 
         $results = [
-            'items' => $items_array,
```
Comment (snipe) [inline app/Http/Transformers/SelectlistTransformer.php]: @uberbrady can we switch this back to `items` here too, for the benefit of consistency in the API?

**Review by snipe — CHANGES_REQUESTED** [review]
See inline

File: app/Http/Transformers/SelectlistTransformer.php (hunk 1 above)
Comment (uberbrady) [reply app/Http/Transformers/SelectlistTransformer.php]: yup!
