### PR TITLE
Fixed #8709 - Bulk Deletion of Categories, Suppliers, Manufa...

### LINKED ISSUE #8709: Bulk deletion of asset Categories, Suppliers, Manufacturers...
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Hi, I have the same problem as in ["Bulk deletion of asset models #3416"](https://github.com/snipe/snipe-it/issues/3416)
but with all another assets: Category, Suppliers, Manufacturers, etc - like in the picture. I cannot delete all assets on one time/click

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Categories, Manufacturers, Suppliers...'

**Expected behavior**
I would have there something like "select all and delete all".

**Screenshots**
image
image
image

**Server (please complete the following information):**
 - Snipe-IT Version: Version v5.0.5-pre - build 5457 (master)
 - OS: [e.g. Ubuntu, CentOS]: Debian 10 buster
 - Web Server: [e.g. Apache, IIS]: Apache/2.4.38 (Debian)
 - PHP Version: PHP 7.3.19-1~deb10u1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

### PR DESCRIPTION
**Pull request by spencerrlongg**
Alright, this looks like more than it is. I've gone ahead and refactored the existing delete controller methods into actions with new exceptions to be thrown when one of the disallowed conditions has been met. 

There's few reasons for this. 

1. The actions make this so that the bulk controllers and the standard controllers are all nearly identical, the only differences are the foreach and the error gathering. 

2. As we continue to expand our use of actions (fingers crossed) those Exceptions are re-usable and create a simple pattern for what to do when one of these things happen

3. If we need to make a change to how we delete one of these things, it's painfully simple to go do that in one place and have it work the same across the board (for instance, there were some inconsistencies while I was doing this, like not always also deleting the picture associated with the deleted object)

On the frontend, I went ahead and just duplicated `asset-bulk-actions.blade.php` to similar ones for the new supported models, I started writing a bunch of conditionals in the original blade with the intention of re-using it and decided it was starting to look too messy. 

What should probably happen eventually is a single component with good props that can handle all of these, but the amount of refactor that would've required seemed too much for this PR considering it's already fairly large and has taken some time. 

I'm sure there will be some questions and I look forward to the conversation!

### CODE REVIEW

**Comment by spencerrlongg** [comment]
Oops, forgot to rename maintenances - done!

File: app/Actions/Categories/DestroyCategoryAction.php [hunk 1]
```diff
@@ -0,0 +1,61 @@
+<?php
+
+namespace App\Actions\Categories;
+
+use App\Exceptions\ModelIsNotDeletable;
```
Comment (uberbrady) [inline app/Actions/Categories/DestroyCategoryAction.php]: I would go with `Item` or @snipe says `SnipeModel` - or you could just go with:

- `IsNotDeletable`
-

File: app/Actions/Manufacturers/DeleteManufacturerAction.php [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+    {
+        $manufacturer->loadCount([
+            'assets as assets_count',
+            'accessories as accessories_count',
+            'consumables as consumables_count',
+            'components as components_count',
+            'licenses as licenses_count',
+        ]);
+
+        if ($manufacturer->assets_count > 0) {
```
Comment (uberbrady) [inline app/Actions/Manufacturers/DeleteManufacturerAction.php:33]: I kinda feel like all these checks could get put in something like:

```
public function throwIfNotDeletable()
{
   //grab counts, throw the new exceptions as appropriate
}
```

And then you can make `is_deletable()` just be like this:
```
public function is_deletable()
{
   try {
      $this->throwIfNotDeletable();
      } catch (BaseExceptionWhateverItsCalled $e) {
        return false;
   } catch (Exception $e) {
     //do something else?
  }
  }
  ```

File: app/Http/Controllers/Api/ManufacturersController.php [hunk 3]
```diff
@@ -184,19 +191,18 @@ public function update(ImageUploadRequest $request, $id) : JsonResponse
...
         $this->authorize('delete', $manufacturer);
-
-        if ($manufacturer->isDeletable()) {
-            $manufacturer->delete();
-            return response()->json(Helper::formatStandardApiResponse('success', null,  trans('admin/manufacturers/message.delete.success')));
+        try {
+            DeleteManufacturerAction::run($manufacturer);
+        } catch (ModelStillHasChildren $e) {
+            return response()->json(Helper::formatStandardApiResponse('error', null, trans('admin/manufacturers/message.assoc_users')));
+        } catch (\Exception $e) {
```
Comment (uberbrady) [inline app/Http/Controllers/Api/ManufacturersController.php:201]: We caught `\Throwable` before, should we do that here?

Comment (uberbrady) [reply app/Http/Controllers/Api/ManufacturersController.php:201]: @marcusmoore mentions we did _not_ do the `report()` here and should

File: resources/lang/en-US/admin/categories/message.php [hunk 4]
```diff
@@ -18,9 +18,17 @@
...
-        'confirm'   => 'Are you sure you wish to delete this category?',
-        'error'   => 'There was an issue deleting the category. Please try again.',
-        'success' => 'The category was deleted successfully.'
+        'not_found'              => 'Category not found.',
+        'confirm'                => 'Are you sure you wish to delete this category?',
+        'error'                  => 'There was an issue deleting the category. Please try again.',
+        'success'                => 'The category was deleted successfully.',
+        'bulk_success'           => 'The Categories were deleted successfully.',
+        'bulk_assoc_assets'      => ':category_name still has associated assets and cannot be deleted. Please update your assets to no longer reference this supplier and try again.',
+        'bulk_assoc_accessories' => ':category_name still has associated accessories and cannot be deleted. Please update your accessories to no longer reference this supplier and try again.',
```
Comment (uberbrady) [inline resources/lang/en-US/admin/categories/message.php]: s/supplier/category/

File: resources/lang/en-US/admin/categories/message.php [hunk 5]
```diff
@@ -18,9 +18,17 @@
...
+        'bulk_assoc_consumables' => ':category_name still has associated consumables and cannot be deleted. Please update your consumables to no longer reference this supplier and try again.',
+        'bulk_assoc_components'  => ':category_name still has associated components and cannot be deleted. Please update your components to no longer reference this supplier and try again.',
+        'bulk_assoc_licenses'    => ':category_name still has associated licenses and cannot be deleted. Please update your licenses to no longer reference this supplier and try again.',
+        'bulk_assoc_models'      => ':category_name still has associated asset models and cannot be deleted. Please update your asset models to no longer reference this supplier and try again.',
```
Comment (uberbrady) [inline resources/lang/en-US/admin/categories/message.php]: (etc.)

File: resources/lang/en-US/admin/manufacturers/message.php [hunk 6]
```diff
@@ -22,9 +22,16 @@
...
     'delete' => array(
-        'confirm'   => 'Are you sure you wish to delete this manufacturer?',
+        'not_found'              => 'Manufacturer not found.',
+        'confirm' => 'Are you sure you wish to delete this manufacturer?',
         'error'   => 'There was an issue deleting the manufacturer. Please try again.',
-        'success' => 'The Manufacturer was deleted successfully.'
+        'success'                => 'The Manufacturer was deleted successfully.',
+        'bulk_success'           => 'The Manufacturers were deleted successfully.',
+        'bulk_assoc_assets'      => ':manufacturer_name still has associated assets and cannot be deleted. Please update your assets to no longer reference this supplier and try again.',
+        'bulk_assoc_accessories' => ':manufacturer_name still has associated accessories and cannot be deleted. Please update your accessories to no longer reference this supplier and try again.',
```
Comment (uberbrady) [inline resources/lang/en-US/admin/manufacturers/message.php]: also 'supplier' here - copypasta

Comment (uberbrady) [reply resources/lang/en-US/admin/manufacturers/message.php]: @snipe says:

maybe we can do this more generic - 

```
:something_name still has associated :thingees and cannot be deleted. 
Please update your :thingees to no longer reference this :something_name and try again
```

Comment (uberbrady) [reply resources/lang/en-US/admin/manufacturers/message.php]: But do we run into a double-translation problem here?

"Por favor, updata-se suas categories para não referencar os categories and try again..."

According to @snipe we actually *do* do the trans() thing where we pass 'categories' => 'categorarios' or whatever. @snipe says she has an example.

File: resources/views/components/tables/bulk-actions.blade.php [hunk 7]
```diff
@@ -0,0 +1,30 @@
...
+        {{-- The sort and order will only be used if the cookie is actually empty (like on first-use) --}}
+        <input name="sort" type="hidden" value="assets.id">
+        <input name="order" type="hidden" value="asc">
+        <label for="bulk_actions">
+        <span class="sr-only">
+            {{ trans('button.bulk_actions') }}
+        </span>
+        </label>
+        <select name="bulk_actions" class="form-control select2" aria-label="bulk_actions" style="min-width: 350px;">
+            @can('delete', \App\Models\Asset::class)
```
Comment (uberbrady) [inline resources/views/components/tables/bulk-actions.blade.php]: This is components, not Asset?

File: resources/views/partials/manufacturer-bulk-actions.blade.php [hunk 8]
```diff
@@ -0,0 +1,30 @@
...
+            {{-- ...basically should end up being a big component, but felt too big an undertaking for this PR --}}
+            action="{{ route('manufacturers.bulk.delete') }}"
+            accept-charset="UTF-8"
+            class="form-inline"
+            id="{{ (isset($id_formname)) ? $id_formname : 'manufacturersBulkForm' }}"
+    >
+        @csrf
+
+        {{-- The sort and order will only be used if the cookie is actually empty (like on first-use) --}}
+        <input name="sort" type="hidden" value="assets.id">
```
Comment (uberbrady) [inline resources/views/partials/manufacturer-bulk-actions.blade.php]: sort by assets.id?

**Review by uberbrady — CHANGES_REQUESTED** [review]
Here's the stuff we went over when we went through this PR - I'm feeling pretty good about it, myself. Please let me and/or @snipe know when you've been able to address those - or ping me in Slack if you have any specific questions.

File: app/Http/Controllers/Api/ManufacturersController.php (hunk 3 above)
Comment (spencerrlongg) [reply app/Http/Controllers/Api/ManufacturersController.php:201]: I actually meant to catch `\Exception` on all of them, so I'm switching to that to make it consistent. 
image

File: resources/lang/en-US/admin/manufacturers/message.php (hunk 6 above)
Comment (spencerrlongg) [reply resources/lang/en-US/admin/manufacturers/message.php]: @snipe could I get the example of this when you've got a sec?

File: app/Actions/Categories/DestroyCategoryAction.php (hunk 1 above)
Comment (spencerrlongg) [reply app/Actions/Categories/DestroyCategoryAction.php]: renamed to `Item....`

**Comment by spencerrlongg** [comment]
@uberbrady / @snipe this should be ready to go now

File: resources/lang/en-US/admin/categories/message.php [hunk 9]
```diff
@@ -18,9 +18,11 @@
     ),
 
     'delete' => array(
-        'confirm'   => 'Are you sure you wish to delete this category?',
-        'error'   => 'There was an issue deleting the category. Please try again.',
-        'success' => 'The category was deleted successfully.'
+        'not_found'              => 'Category not found.',
```
Comment (snipe) [inline resources/lang/en-US/admin/categories/message.php]: I think we want to use the generic category (etc) not found strings here to avoid duplicated translations.

File: resources/views/components/tables/bulk-actions.blade.php [hunk 10]
```diff
@@ -0,0 +1,35 @@
...
+            method="POST"
+            action="{{ $action_route }}"
+            accept-charset="UTF-8"
+            class="form-inline"
+            id="{{  $id_formname }}"
+    >
+        @csrf
+
+        {{--        The sort and order will only be used if the cookie is actually empty (like on first-use)--}}
+        <input name="sort" type="hidden" value="{{`$model_name.id`}}">
```
Comment (snipe) [inline resources/views/components/tables/bulk-actions.blade.php:21]: Are these backticks deliberate? They look sorta weird here.

File: resources/views/manufacturers/index.blade.php [hunk 11]
```diff
@@ -30,7 +30,17 @@
...
-
+                <x-tables.bulk-actions
+                        id_divname='manufacturersBulkEditToolbar'
+                        action_route="{{route('manufacturers.bulk.delete')}}"
+                        id_formname="manufacturersBulkForm"
+                        id_button="bulkManufacturerEditButton"
+                        model_name="manufacturer"
+                >
+                    @can('delete', App\Models\Manufacturer::class)
+                        <option>Delete</option>
```
Comment (snipe) [inline resources/views/manufacturers/index.blade.php]: Please use translations here

File: resources/views/suppliers/index.blade.php [hunk 12]
```diff
@@ -12,15 +12,35 @@
 
 <div class="row">
   <div class="col-md-12">
-    <div class="box box-default">
```
Comment (snipe) [inline resources/views/suppliers/index.blade.php:15]: Why was `box-default` removed here?

File: app/Actions/Suppliers/DestroySupplierAction.php [hunk 13]
```diff
@@ -0,0 +1,50 @@
...
+     * @throws ItemStillHasLicenses
+     * @throws ItemStillHasAssets
+     * @throws ItemStillHasMaintenances
+     */
+    static function run(Supplier $supplier): bool
+    {
+        $supplier->loadCount([
+            'maintenances as maintenances_count',
+            'assets as assets_count',
+            'licenses as licenses_count'
```
Comment (snipe) [inline app/Actions/Suppliers/DestroySupplierAction.php]: Suppliers also have accessories, consumables, and components.

**Review by snipe — CHANGES_REQUESTED** [review]
Some comments inline

File: resources/views/suppliers/index.blade.php (hunk 12 above)
Comment (spencerrlongg) [reply resources/views/suppliers/index.blade.php:15]: i think it was when i was experimenting around with adding the bulk dropdown to the table and was having some issues, added back and seems like it's fine.

File: resources/views/components/tables/bulk-actions.blade.php (hunk 10 above)
Comment (spencerrlongg) [reply resources/views/components/tables/bulk-actions.blade.php:21]: Yeah i'm not sure why, but they're necessary to get it compiling.

File: resources/lang/en-US/admin/categories/message.php (hunk 9 above)
Comment (spencerrlongg) [reply resources/lang/en-US/admin/categories/message.php]: Not sure what translation you mean

Comment (spencerrlongg) [reply resources/lang/en-US/admin/categories/message.php]: ah, found them

**Comment by spencerrlongg** [comment]
Should be good to go now.

File: app/Actions/Suppliers/DestroySupplierAction.php [hunk 14]
```diff
@@ -0,0 +1,72 @@
...
+            throw new ItemStillHasConsumables($supplier);
+        }
+
+        if ($supplier->components_count > 0) {
+            throw new ItemStillHasComponents($supplier);
+        }
+
+        if ($supplier->image) {
+            try {
+                Storage::disk('public')->delete('suppliers/'.$supplier->image);
```
Comment (snipe) [inline app/Actions/Suppliers/DestroySupplierAction.php:62]: If we restore these categories, etc, the image will be broken

File: resources/lang/en-US/admin/categories/message.php [hunk 15]
```diff
@@ -18,9 +18,10 @@
     ),
 
     'delete' => array(
-        'confirm'   => 'Are you sure you wish to delete this category?',
-        'error'   => 'There was an issue deleting the category. Please try again.',
-        'success' => 'The category was deleted successfully.'
+        'confirm'                => 'Are you sure you wish to delete this category?',
+        'error'                  => 'There was an issue deleting the category. Please try again.',
+        'success'                => 'The category was deleted successfully.',
+        'bulk_success'           => 'The Categories were deleted successfully.',
```
Comment (snipe) [inline resources/lang/en-US/admin/categories/message.php:24]: Inconsistent capitalization here
