### PR TITLE
Fixed Unaccepted Assets Reports Resend acceptance reminder email function

### LINKED ISSUE #15887: Reminder for unaccepted assets no longer working
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi

Still quite new to Snipe so apologies if i've missed any steps in troubleshooting.

Since the upgrade from v7.0.13 to v7.1.14 (and subsiquently to v7.1.15), unaccepted asset reminder mails are no longer working. 

When clicking on the Send Reminder button, a message appears saying "Success: Reminder sent", however no mail is recieved anywhere. 

All other mail notifications on the platform are working without any issues.

I tried enabling and trawling through debug mode, but I couldn't find any errors. 

Interestingly, if I run php artisan snipeit:acceptance-reminder -vvvv, a reminder **is** sent to all users with unaccepted assets - This is a perfectly fine workaround for me at the moment as we are just about to migrate over to snipe and are getting all users to re-accepet their assets and we will be sending out these reminders regularly during the process.

### Reproduction steps

1. Navigate to Reports -> Unaccepted assets
2. Click on the orange "send reminder" button next to a user with unaccepted assets
3. "Success: Reminder sent" message is displayed
4. No reminder mail appears anywhere
5. Tested other mail notifications e.g. asset checkin/checkout and these work perfectly. Test mail in system settings also works. 
...

### Expected behavior

The user with the unaccepted asset should recieve a mail reminding them to accept their asset.

### Screenshots

_No response_

### Snipe-IT Version

7.1.15

### Operating System

Ubuntu 24.04

### Web Server

Apache

### PHP Version

8.3.6

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
This fixes the Resend acceptance reminder on the Unaccepted Assets Report.

Fixes #15887

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/Http/Controllers/ReportsController.php [hunk 1]
```diff
@@ -1152,20 +1154,12 @@ public function sentAssetAcceptanceReminder(Request $request) : RedirectResponse
         }
 
         // Only send notification if assigned
-        if ($assetItem->assignedTo) {
+        if ($assetItem->assignedTo->email) {
```
Comment (snipe) [inline app/Http/Controllers/ReportsController.php]: I think we might need to check that `$assetItem->assignedTo` is not null here before trying to get the property, no?

Comment (Godmartinz) [reply app/Http/Controllers/ReportsController.php]: done 👍

File: app/Http/Controllers/ReportsController.php [hunk 2]
```diff
@@ -1152,22 +1154,14 @@ public function sentAssetAcceptanceReminder(Request $request) : RedirectResponse
...
-                Notification::locale(Setting::getSettings()->locale)->send(
-                    $assetItem->assignedTo,
-                    new CheckoutAssetNotification($assetItem, $assetItem->assignedTo, $logItem->user, $acceptance, $logItem->note)
-                );
             } else {
-                Notification::send(
-                    $assetItem->assignedTo,
-                    new CheckoutAssetNotification($assetItem, $assetItem->assignedTo, $logItem->user, $acceptance, $logItem->note)
-                );
+                Mail::to($assetItem->assignedTo->email)->send((new CheckoutAssetMail($assetItem, $assetItem->assignedTo, $logItem->user, $logItem->note, $acceptance)));
```
Comment (marcusmoore) [inline app/Http/Controllers/ReportsController.php]: I think the `if` check for `$assetItem->assignedTo->locale` was accidentally removed?

This line uses `$assetItem->assignedTo->email` in an `else` that checked to see if it existed. In other words, this `else` could fail because `$assetItem->assignedTo->email` is falsy here.

**Review by marcusmoore — CHANGES_REQUESTED** [review]
One question

File: app/Http/Controllers/ReportsController.php (hunk 2 above)
Comment (Godmartinz) [reply app/Http/Controllers/ReportsController.php]: updated, also made it a bit more readable.

**Comment by Godmartinz** [comment]
I notice the maintenance delete test is failing here..but locally they all pass 🤔

**Comment by marcusmoore** [comment]
It was a fluke. Re-running got them back to green. I'll review in a bit.

**Review by marcusmoore — APPROVED** [review]
Looks good to me 👍🏾
