### PR TITLE
replace env with config variable for from address

### LINKED ISSUE #15813: Asset checkin/out emails not being sent
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The test email sending function works fine. However, the checkin and checkout emails are not being sent.
I have checked the settings of the asset categories and the option to send email, EULA, and asset accettance are configured properly.
The user's email addresses are set correctly too. 

### Reproduction steps

1. Checked the email settings in the categories
2.Checked the functioning of the emails via the test function
3.Tried the debug mode but cannot find any errors 
...

### Expected behavior

Email being sent on checkin/checkout of an asset

### Screenshots

_No response_

### Snipe-IT Version

7.1.14 build 15942

### Operating System

Docker

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### LINKED ISSUE #15834: Issue with Receiving Check-In/Check-Out Emails
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi Team,

I noticed that after checking in/out, I am not receiving the corresponding emails. Could you please check and assist with this issue?

### Reproduction steps

1.Checked the email settings in the categories
2.Checked the functioning of the emails via the test function
3.Tried the debug mode but cannot find any errors

### Expected behavior

Email being sent on checkin/checkout of an asset

### Screenshots

_No response_

### Snipe-IT Version

v7.1.14

### Operating System

CentOS Linux 7

### Web Server

Apache/2.4.6

### PHP Version

PHP 8.3.8

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Godmartinz**
# Description
This replaces the env variable being used in the from field for mail notifications with the config variable `mail.from.address`

Fixes #15813

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* PHP version:
* MySQL version
* Webserver version
* OS version

# Checklist:

- [ ] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [ ] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by snipe** [comment]
Looks like we have some failing tests here - can you take a look?

**Comment by Godmartinz** [comment]
@snipe tests are good now

**Comment by snipe** [comment]
Why did this end up back in draft?

**Comment by marcusmoore** [comment]
Not ready to go as is. Planning on wrapping up today.

File: config/mail.php [hunk 1]
```diff
@@ -237,7 +237,7 @@
     */
 
     'from' => [
-        'address' => env('MAIL_FROM_ADDR', null),
+        'address' => env('MAIL_FROM_ADDR', env('MAIL_ENV_FROM_ADDR')),
```
Comment (marcusmoore) [inline config/mail.php]: Let's keep this as it was before. We talked this through and `MAIL_ENV_FROM_ADDR` wouldn't be available to us to use here.

```suggestion
        'address' => env('MAIL_FROM_ADDR', null),
```

**Review by marcusmoore — CHANGES_REQUESTED** [review]

**Comment by Godmartinz** [comment]
@marcusmoore @snipe should be good to go now.

**Review by marcusmoore — APPROVED** [review]
I haven't tested this via docker myself but I believe this is the fix. 👍🏾
