### PR TITLE
Fixed accessories and consumables not being logged correctly during bulk check-in

### LINKED ISSUE #15109: Problem with Bulk Checkin
### Debug mode

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When an individual user has Accessories and/or Consumables on him and after I want to do Bulk Checkin / Delete Users by clicking on that user, a list of everything he has on him appears.
When I click on the box that I want to bulk check in on that user, I select the status and click submit. on the Dashboard and under Recent Activity as well as under user history, it does not show me the correct checkin Accessories and/or Consumables, but writes random ones that were not under that user at all.

### Reproduction steps

I've checked the above with multiple versions of the app as well as the latest available, but the problem still persists.

### Expected behavior

Under Recent Activity as well as under User History after Bulk Checkin / Delete Users it should show the exact Accessories and/or Consumables or anything else that was actually on it.

### Screenshots

_No response_

### Snipe-IT Version

v7.0.9 

### Operating System

Ubuntu, Windows

### Web Server

Apache, IIS

### PHP Version

8.1.2 or greater

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marcusmoore**
# Description

This PR fixes an issue where accessories and consumables being bulk checked in were not being logged correctly. See [this comment](https://github.com/snipe/snipe-it/issues/15109#issuecomment-2244049200) for more details.

In the process the PR adds tests around the `destroy` method in `BulkUsersController`. 

Fixes #15109

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: app/Http/Controllers/Users/BulkUsersController.php [hunk 1]
```diff
@@ -291,6 +285,34 @@ protected function logItemCheckinAndDelete($items, $itemType)
...
+            $logAction = new Actionlog();
+            $logAction->item_id = $consumableUserRow->consumable_id;
+            $logAction->item_type = Consumable::class;
+            $logAction->target_id = $consumableUserRow->assigned_to;
+            $logAction->target_type = User::class;
+            $logAction->user_id = Auth::id();
+            $logAction->note = 'Bulk checkin items';
+            $logAction->logaction('checkin from');
+        }
+    }
```
Comment (marcusmoore) [inline app/Http/Controllers/Users/BulkUsersController.php:314]: Not loving the duplication but there is enough difference that using explicit method names instead of passing a handful of parameters is cleaner I think
