### PR TITLE
Fixed #11393 - reject acceptance if no file is present

### LINKED ISSUE #11393: Check Browser Compatibility for Signature Pad / Add Approval Queue - Was: Empty Signature at Asset Acceptance
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

There is no check in place to confirm that the user has actually signed in the Asset Acceptance form.
When the user leaves the signature part completely empty and accepts the EULA, it accepts without any error.

Normally, it should show an error message stating that the signature is missing.

### Reproduction steps

1. Create an Asset Category with "Require users to confirm acceptance of assets in this category" check box enabled.
2. On the General Settings page, make sure that "Require Signature" option is Yes
3. Check out an asset to any user and check the user's mail for the link to accept the asset.
4. Accept the Terms and click Submit without signing.
...

### Expected behavior

Normally an error message should appear asking the user to sign.

### Screenshots

_No response_

### Snipe-IT Version

6.0.4

### Operating System

Windows

### Web Server

WAMP Server

### PHP Version

7.4.26

### Operating System

Windows

### Browser

Google Chrome

### Version

102

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by snipe**
This is an edge case, but for certain companies where asset acceptance is part of a legal process, the signature validation system (checking to see if the user actually signed it) could be bypassed by turning off javascript, or by using a really old browser like IE.

Screen Shot 2022-06-30 at 9 00 19 PM

Fixes #11393

### CODE REVIEW

**Review by uberbrady — APPROVED** [review]
This is *NOICE*. Very crisp, clean work. Love the server-side implementation. This is really going to solve a *lot* of problems; excellent work!

File: resources/lang/en/general.php [hunk 1]
```diff
@@ -363,5 +363,6 @@
     'purge_not_allowed'     => 'Purging deleted data has been disabled in the .env file. Contact support or your systems administrator.',
     'backup_delete_not_allowed'     => 'Deleting backups has been disabled in the .env file. Contact support or your systems administrator.',
     'additional_files'           => 'Additional Files',
+    'shitty_browser'        => 'No signature detected. If you are using an older browser, please use a more modern browser to complete your asset acceptance.',
```
Comment (mikeroq) [inline resources/lang/en/general.php:366]: This kills me 🤣🤣

Comment (snipe) [reply resources/lang/en/general.php:366]: Gotta have fun where you can, right? :P
